Test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,6 +18,7 @@ jobs:
     - name: Test
       run: swift test --xunit-output output.xml --parallel
     - name: Upload test results
+      if: success() || failure()
       uses: actions/upload-artifact@v4
       with:
         name: test-results
@@ -48,7 +49,7 @@ jobs:
         brew install htmlq
         result=`echo "${{ steps.publish-test-report.outputs.detailed_summary }}" | htmlq table tr td -t`
         result="${result//$'\n'/'%0A'}"
-        echo "failed_result=$result" >> $GITHUB_OUTPUT
+        echo "failed_result=" >> $GITHUB_OUTPUT
       env:
         HOMEBREW_NO_AUTO_UPDATE: 1
     - name: Echo failed result
